version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    image: trayden/quickshare-backend:latest
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

  # Optional: Add Redis for production-scale file metadata storage
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped
  #   command: redis-server --appendonly yes

# volumes:
#   redis_data: